name: CI
on: push
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: giautm
          GIT_AUTHOR_EMAIL: giau.tmg@gmail.com
          GIT_COMMITTER_NAME: giautm
          GIT_COMMITTER_EMAIL: giau.tmg@gmail.com
        run: npx semantic-release
        
